SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

 CREATE VIEW [dbo].[V_REPMM_MEDB] as

 /*
1	PANISTERIA
2	LIBRERIA
3	GTT
4	PAPAS
5	DONBUFFET
6	MEDITERRANEO
*/

SELECT FECHA,
       ROUND(SUM(DB_CCPN_icg  ),3) AS "DB CCPN icg"  ,
       ROUND(SUM(DB_CCPN_sac  ),3) AS "DB CCPN sac"  ,
       ROUND(SUM(DB_CCPN_delta),3) AS "DB CCPN delta",
       ROUND(SUM(DB_MDS_icg   ),3) AS "DB MDS icg"   ,
       ROUND(SUM(DB_MDS_sac   ),3) AS "DB MDS sac"   ,
       ROUND(SUM(DB_MDS_delta ),3) AS "DB MDS delta" ,
       ROUND(SUM(DB_null_icg  ),3) AS "DB null icg"  ,
       ROUND(SUM(DB_null_sac  ),3) AS "DB null sac"  ,
       ROUND(SUM(DB_null_delta),3) AS "DB null delta"
  FROM (SELECT FECHA,
               DB_CCPN_icg   = CASE NOM_TIENDA  WHEN 'MEDITERRANEO DON BUFFET CCPN' THEN BASE_ICG ELSE NULL END,
               DB_CCPN_sac   = CASE NOM_TIENDA  WHEN 'MEDITERRANEO DON BUFFET CCPN' THEN BASE_DM ELSE NULL END,
               DB_CCPN_delta = CASE NOM_TIENDA  WHEN 'MEDITERRANEO DON BUFFET CCPN' THEN DELTA ELSE NULL END,
               DB_MDS_icg    = CASE NOM_TIENDA  WHEN 'MEDITERRANEO DON BUFFET MDS' THEN BASE_ICG ELSE NULL END,
               DB_MDS_sac    = CASE NOM_TIENDA  WHEN 'MEDITERRANEO DON BUFFET MDS' THEN BASE_DM ELSE NULL END,
               DB_MDS_delta  = CASE NOM_TIENDA  WHEN 'MEDITERRANEO DON BUFFET MDS' THEN DELTA ELSE NULL END,
               DB_null_icg   = CASE NOM_TIENDA  WHEN NULL THEN BASE_ICG ELSE NULL END,
               DB_null_sac   = CASE NOM_TIENDA  WHEN NULL THEN BASE_DM ELSE NULL END,
               DB_null_delta = CASE NOM_TIENDA  WHEN NULL THEN DELTA ELSE NULL END
          FROM VAL_CUADRE_F
         WHERE COD_EMPRESA = '5') AS T
 GROUP BY FECHA
GO