SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE VIEW [dbo].[V_REPMM_MEDP] as

 /*
1	PANISTERIA
2	LIBRERIA
3	GTT
4	PAPAS
5	DONBUFFET
6	MEDITERRANEO
*/

SELECT FECHA,
       ROUND(SUM(MOD_pap_GTT_INT_icg   ),3) AS "MOD papa GTT INT icg"   ,
       ROUND(SUM(MOD_pap_GTT_INT_sac   ),3) AS "MOD papa GTT INT sac"   ,
       ROUND(SUM(MOD_pap_GTT_INT_delta ),3) AS "MOD papa GTT INT delta" ,
       ROUND(SUM(MOD_pap_GTT_NIV1_icg  ),3) AS "MOD papa GTT NIV1 icg"  ,
       ROUND(SUM(MOD_pap_GTT_NIV1_sac  ),3) AS "MOD papa GTT NIV1 sac"  ,
       ROUND(SUM(MOD_pap_GTT_NIV1_delta),3) AS "MOD papa GTT NIV1 delta",
       ROUND(SUM(MOD_pap_MDS_NIV1_icg  ),3) AS "MOD papa MDS NIV1 icg"  ,
       ROUND(SUM(MOD_pap_MDS_NIV1_sac  ),3) AS "MOD papa MDS NIV1 sac"  ,
       ROUND(SUM(MOD_pap_MDS_NIV1_delta),3) AS "MOD papa MDS NIV1 delta",
       ROUND(SUM(MOD_pap_RPCC_icg   ),3) AS "MOD papa RPCC icg"  ,
       ROUND(SUM(MOD_pap_RPCC_sac   ),3) AS "MOD papa RPCC sac"  ,
       ROUND(SUM(MOD_pap_RPCC_delta ),3) AS "MOD papa RPCC delta",
       ROUND(SUM(MOD_pap_null_icg   ),3) AS "MOD papa null icg"  ,
       ROUND(SUM(MOD_pap_null_sac   ),3) AS "MOD papa null sac"  ,
       ROUND(SUM(MOD_pap_null_delta ),3) AS "MOD papa null delta"
  FROM (SELECT FECHA,
               MOD_pap_GTT_INT_icg    = CASE NOM_TIENDA  WHEN 'MEDITERRANEO PAPAS GTT INTERIOR' THEN BASE_ICG ELSE NULL END,
               MOD_pap_GTT_INT_sac    = CASE NOM_TIENDA  WHEN 'MEDITERRANEO PAPAS GTT INTERIOR' THEN BASE_DM ELSE NULL END,
               MOD_pap_GTT_INT_delta  = CASE NOM_TIENDA  WHEN 'MEDITERRANEO PAPAS GTT INTERIOR' THEN DELTA ELSE NULL END,
               MOD_pap_GTT_NIV1_icg   = CASE NOM_TIENDA  WHEN 'MEDITERRANEO PAPAS GTT NIVEL 1' THEN BASE_ICG ELSE NULL END,
               MOD_pap_GTT_NIV1_sac   = CASE NOM_TIENDA  WHEN 'MEDITERRANEO PAPAS GTT NIVEL 1' THEN BASE_DM ELSE NULL END,
               MOD_pap_GTT_NIV1_delta = CASE NOM_TIENDA  WHEN 'MEDITERRANEO PAPAS GTT NIVEL 1' THEN DELTA ELSE NULL END,
               MOD_pap_MDS_NIV1_icg   = CASE NOM_TIENDA  WHEN 'MEDITERRANEO PAPAS MDS NIVEL 1' THEN BASE_ICG ELSE NULL END,
               MOD_pap_MDS_NIV1_sac   = CASE NOM_TIENDA  WHEN 'MEDITERRANEO PAPAS MDS NIVEL 1' THEN BASE_DM ELSE NULL END,
               MOD_pap_MDS_NIV1_delta = CASE NOM_TIENDA  WHEN 'MEDITERRANEO PAPAS MDS NIVEL 1' THEN DELTA ELSE NULL END,
               MOD_pap_RPCC_icg   = CASE NOM_TIENDA  WHEN 'MEDITERRANEO PAPAS REAL PLAZA CENTRO CIVICO' THEN BASE_ICG ELSE NULL END,
               MOD_pap_RPCC_sac   = CASE NOM_TIENDA  WHEN 'MEDITERRANEO PAPAS REAL PLAZA CENTRO CIVICO' THEN BASE_DM ELSE NULL END,
               MOD_pap_RPCC_delta = CASE NOM_TIENDA  WHEN 'MEDITERRANEO PAPAS REAL PLAZA CENTRO CIVICO' THEN DELTA ELSE NULL END,
               MOD_pap_null_icg   = CASE NOM_TIENDA  WHEN NULL THEN BASE_ICG ELSE NULL END,
               MOD_pap_null_sac   = CASE NOM_TIENDA  WHEN NULL THEN BASE_DM ELSE NULL END,
               MOD_pap_null_delta = CASE NOM_TIENDA  WHEN NULL THEN DELTA ELSE NULL END
          FROM VAL_CUADRE_F
         WHERE COD_EMPRESA = '4') AS T
 GROUP BY FECHA
GO