SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE VIEW [dbo].[V_REPMM_PANI] AS
  
 /*
1	PANISTERIA
2	LIBRERIA
3	GTT
4	PAPAS
5	DONBUFFET
6	MEDITERRANEO
*/

SELECT FECHA,
       ROUND(SUM(PANI_CCPN_icg  ),3) AS "PANI CCPN icg",
       ROUND(SUM(PANI_CCPN_sac  ),3) AS "PANI CCPN sac",
       ROUND(SUM(PANI_CCPN_delta),3) AS "PANI CCPN delta",
       ROUND(SUM(PANI_MDS_icg   ),3) AS "PANI MDS icg",
       ROUND(SUM(PANI_MDS_sac   ),3) AS "PANI MDS sac",
       ROUND(SUM(PANI_MDS_delta ),3) AS "PANI MDS delta",
       ROUND(SUM(PANI_null_icg  ),3) AS "PANI null icg",
       ROUND(SUM(PANI_null_sac  ),3) AS "PANI null sac",
       ROUND(SUM(PANI_null_delta),3) AS "PANI null delta"
  FROM (SELECT FECHA,
               PANI_CCPN_icg   = CASE NOM_TIENDA  WHEN 'PANISTERIA CCPN' THEN BASE_ICG ELSE NULL END,
               PANI_CCPN_sac   = CASE NOM_TIENDA  WHEN 'PANISTERIA CCPN' THEN BASE_DM ELSE NULL END,
               PANI_CCPN_delta = CASE NOM_TIENDA  WHEN 'PANISTERIA CCPN' THEN DELTA ELSE NULL END,
               PANI_MDS_icg    = CASE NOM_TIENDA  WHEN 'PANISTERIA MDS' THEN BASE_ICG ELSE NULL END,
               PANI_MDS_sac    = CASE NOM_TIENDA  WHEN 'PANISTERIA MDS' THEN BASE_DM ELSE NULL END,
               PANI_MDS_delta  = CASE NOM_TIENDA  WHEN 'PANISTERIA MDS' THEN DELTA ELSE NULL END,
               PANI_null_icg   = CASE NOM_TIENDA  WHEN NULL THEN BASE_ICG ELSE NULL END,
               PANI_null_sac   = CASE NOM_TIENDA  WHEN NULL THEN BASE_DM ELSE NULL END,
               PANI_null_delta = CASE NOM_TIENDA  WHEN NULL THEN DELTA ELSE NULL END
          FROM VAL_CUADRE_F
         WHERE COD_EMPRESA = '1') AS T
 GROUP BY FECHA
GO