CREATE TABLE [dbo].[TIPOSPAGO] (
  [COD_EMPRESA] [int] NOT NULL,
  [COD_TIPOPAGO] [nvarchar](2) NOT NULL,
  [NOM_TIPO_PAGO] [nvarchar](35) NULL,
  [METALICO] [nchar](1) NULL,
  [TARJETA] [nchar](1) NULL,
  CONSTRAINT [PK_TIPOSPAGO] PRIMARY KEY CLUSTERED ([COD_EMPRESA], [COD_TIPOPAGO])
)
ON [PRIMARY]
GO