CREATE TABLE [dbo].[SECCIONES] (
  [COD_EMPRESA] [int] NOT NULL,
  [COD_DPTO] [int] NOT NULL,
  [COD_SECCION] [int] NOT NULL,
  [NOM_SECCION] [nvarchar](25) NULL,
  CONSTRAINT [PK_SECCIONES] PRIMARY KEY CLUSTERED ([COD_EMPRESA], [COD_DPTO], [COD_SECCION])
)
ON [PRIMARY]
GO