CREATE TABLE [dbo].[TIPOSERVICIOSDELIVERY] (
  [COD_EMPRESA] [int] NOT NULL,
  [TIPO] [int] NOT NULL,
  [DESCRIPCION] [nvarchar](35) NULL,
  [TASAESPECIAL] [bit] NULL,
  [IMAGEN] [image] NULL,
  [IMPORTEMINIMO] [float] NULL,
  [ACTIVARCASHDRO] [bit] NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO