CREATE TABLE [dbo].[ARTICULOSCAMPOSLIBRES] (
  [COD_EMPRESA] [int] NOT NULL,
  [CODARTICULO] [int] NOT NULL,
  [CODMATSAP] [nvarchar](15) NULL,
  [CODIGOPRODSUNAT] [nvarchar](20) NULL,
  [DESCRIPCION_LARGA] [nvarchar](100) NULL,
  [DESCRIPCION_VIETA] [nvarchar](100) NULL
)
ON [PRIMARY]
GO