CREATE TABLE [dbo].[PRECIOSVENTA] (
  [COD_EMPRESA] [int] NOT NULL,
  [COD_TARIFA] [int] NOT NULL,
  [CODARTICULO] [int] NOT NULL,
  [PBRUTO] [float] NULL,
  [DTO] [float] NULL,
  [PNETO] [float] NULL,
  [PNETOANTERIOR] [float] NULL,
  [BENEFICIO] [float] NULL,
  [COD_MONEDA] [int] NULL,
  [FECHAMODIFICADO] [datetime] NULL,
  [DESCATALOGADO] [bit] NULL,
  CONSTRAINT [PK_PRECIOSVENTA] PRIMARY KEY CLUSTERED ([COD_EMPRESA], [COD_TARIFA], [CODARTICULO])
)
ON [PRIMARY]
GO