CREATE TABLE [dbo].[FAMILIAS] (
  [COD_EMPRESA] [int] NOT NULL,
  [COD_DPTO] [int] NOT NULL,
  [COD_SECCION] [int] NOT NULL,
  [COD_FAMILIA] [int] NOT NULL,
  [NOM_FAMILIA] [nvarchar](25) NULL,
  CONSTRAINT [PK_FAMILIAS] PRIMARY KEY CLUSTERED ([COD_EMPRESA], [COD_DPTO], [COD_SECCION], [COD_FAMILIA])
)
ON [PRIMARY]
GO