CREATE TABLE [dbo].[FORMASPAGO] (
  [COD_EMPRESA] [int] NOT NULL,
  [COD_FORMAPAGO] [nvarchar](6) NOT NULL,
  [NOM_FORMA_PAGO] [nvarchar](30) NULL,
  [COD_MONEDA] [int] NULL,
  [VISIBLEFRONT] [nchar](1) NULL,
  CONSTRAINT [PK_FORMASPAGO] PRIMARY KEY CLUSTERED ([COD_EMPRESA], [COD_FORMAPAGO])
)
ON [PRIMARY]
GO