CREATE TABLE [dbo].[MARCA] (
  [COD_EMPRESA] [int] NOT NULL,
  [COD_MARCA] [int] NOT NULL,
  [NOM_MARCA] [nvarchar](25) NULL,
  CONSTRAINT [PK_MARCA] PRIMARY KEY CLUSTERED ([COD_EMPRESA], [COD_MARCA])
)
ON [PRIMARY]
GO