CREATE TABLE [dbo].[IMPUESTOS] (
  [COD_EMPRESA] [int] NOT NULL,
  [TIPOIMPUESTO] [int] NOT NULL,
  [NOM_IMPUESTO] [nvarchar](50) NULL,
  [IVA] [float] NULL,
  [RECARGO] [float] NULL,
  CONSTRAINT [PK_IMPUESTOS] PRIMARY KEY CLUSTERED ([COD_EMPRESA], [TIPOIMPUESTO])
)
ON [PRIMARY]
GO