CREATE TABLE [dbo].[DEPARTAMENTO] (
  [COD_EMPRESA] [int] NOT NULL,
  [COD_DPTO] [int] NOT NULL,
  [NOM_DPTO] [nvarchar](25) NULL,
  CONSTRAINT [PK_Departamento] PRIMARY KEY CLUSTERED ([COD_EMPRESA], [COD_DPTO])
)
ON [PRIMARY]
GO