CREATE TABLE [dbo].[VENDEDORES] (
  [COD_EMPRESA] [int] NOT NULL,
  [CODVENDEDOR] [int] NOT NULL,
  [NOMBRECORTO] [nvarchar](10) NULL,
  [NOMVENDEDOR] [nvarchar](255) NULL,
  [TIPOUSUARIO] [int] NULL,
  [TIPOEMPLEADO] [int] NULL,
  [ACTIVO] [nchar](1) NULL,
  [DESCATALOGADO] [nchar](1) NULL,
  CONSTRAINT [PK_VENDEDORES] PRIMARY KEY CLUSTERED ([COD_EMPRESA], [CODVENDEDOR])
)
ON [PRIMARY]
GO