CREATE TABLE [dbo].[LINEA] (
  [COD_EMPRESA] [int] NOT NULL,
  [COD_MARCA] [int] NOT NULL,
  [COD_LINEA] [int] NOT NULL,
  [NOM_LINEA] [nvarchar](25) NULL,
  CONSTRAINT [PK_LINEA] PRIMARY KEY CLUSTERED ([COD_EMPRESA], [COD_MARCA], [COD_LINEA])
)
ON [PRIMARY]
GO